# coding: utf-8

"""
    X Academy ROV controller

    API to control ROV  # noqa: E501

    OpenAPI spec version: 0.7.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import controller
from controller.api.default_api import DefaultApi  # noqa: E501
from controller.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_motor(self):
        """Test case for motor

        Set PWM value for motor.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
