# coding: utf-8

"""
    X Academy ROV controller

    API to control ROV  # noqa: E501

    OpenAPI spec version: 0.7.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import controller
from controller.models.pwm import Pwm  # noqa: E501
from controller.rest import ApiException


class TestPwm(unittest.TestCase):
    """Pwm unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPwm(self):
        """Test Pwm"""
        # FIXME: construct object with mandatory attributes with example values
        # model = controller.models.pwm.Pwm()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
